#### Importing neccessary libraries

In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

#### Reading the data into df

In [2]:
df = pd.read_csv("Social_Network_Ads.csv")

In [3]:
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

#### Value count for the target variable i.e purchased

In [4]:
df['Purchased'].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

#### Checking is there any NULL values

In [5]:
df.isna().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

#### Storing the independent attributes into x and target attribute into y

In [6]:
x = df.iloc[:,0:2]
y = df.iloc[:,-1]


#### Splitting the data into train test.

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [8]:
print(len(X_train))
print(len(X_test))

320
80


#### Applying the feature Scaling 

In [9]:
from sklearn.preprocessing import StandardScaler

s = StandardScaler()
X_train = s.fit_transform(X_train)
X_test = s.fit_transform(X_test)

In [10]:
print(X_train)

[[ 1.92295008e+00  2.14601566e+00]
 [ 2.02016082e+00  3.78719297e-01]
 [-1.38221530e+00 -4.32498705e-01]
 [-1.18779381e+00 -1.01194013e+00]
 [ 1.92295008e+00 -9.25023920e-01]
 [ 3.67578135e-01  2.91803083e-01]
 [ 1.73156642e-01  1.46942725e-01]
 [ 2.02016082e+00  1.74040666e+00]
 [ 7.56421121e-01 -8.38107706e-01]
 [ 2.70367388e-01 -2.87638347e-01]
 [ 3.67578135e-01 -1.71750061e-01]
 [-1.18475597e-01  2.20395980e+00]
 [-1.47942605e+00 -6.35303205e-01]
 [-1.28500455e+00 -1.06988428e+00]
 [-1.38221530e+00  4.07691369e-01]
 [-1.09058306e+00  7.55356227e-01]
 [-1.47942605e+00 -2.00722133e-01]
 [ 9.50842613e-01 -1.06988428e+00]
 [ 9.50842613e-01  5.81523798e-01]
 [ 3.67578135e-01  9.87132798e-01]
 [ 5.61999628e-01 -8.96051849e-01]
 [-6.04529329e-01  1.45068594e+00]
 [-2.12648508e-02 -5.77359062e-01]
 [-6.04529329e-01  1.88526701e+00]
 [ 1.33968560e+00 -1.41754914e+00]
 [ 1.43689635e+00  9.87132798e-01]
 [ 7.59458956e-02 -8.09135634e-01]
 [-2.12648508e-02 -2.58666276e-01]
 [-2.15686344e-01 -5

In [11]:
print(X_test)

[[-0.49618606  0.56021375]
 [ 0.2389044  -0.59133674]
 [-0.03675452  0.18673792]
 [-0.49618606  0.31122986]
 [-0.03675452 -0.59133674]
 [-0.77184498 -1.52502632]
 [-0.40429975 -1.68064126]
 [ 0.05513178  2.33422397]
 [-1.59882175 -0.03112299]
 [ 1.06588117 -0.80919764]
 [-0.49618606 -0.62245972]
 [-0.67995868 -0.43572181]
 [ 0.14701809 -0.43572181]
 [ 0.33079071  0.24898389]
 [-1.41504914  0.52909077]
 [-0.31241345  1.49390334]
 [ 0.14701809  0.24898389]
 [-1.50693545  0.49796778]
 [ 1.80097163  1.89850216]
 [-0.03675452 -1.46278035]
 [-0.03675452 -0.6847057 ]
 [ 1.06588117  2.33422397]
 [ 0.51456332 -0.56021375]
 [ 1.06588117  1.1204275 ]
 [-1.13939022 -1.27604243]
 [ 1.24965379  2.24085501]
 [-0.67995868  0.56021375]
 [-0.58807237  0.34235285]
 [ 0.14701809 -0.2178609 ]
 [-0.31241345  0.52909077]
 [-1.32316283  0.59133674]
 [ 0.14701809  0.31122986]
 [ 1.98474425 -0.28010688]
 [ 0.14701809 -0.49796778]
 [-1.04750391 -0.34235285]
 [-1.59882175 -0.52909077]
 [-1.23127652  0.37347583]
 

#### Model training  using Decision Tree Classifier

In [12]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

#### Testing the model

In [13]:
y_pred = model.predict(X_test)

#### Confusion Matrix

In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[53  5]
 [ 2 20]]


#### Accuracy Score

In [15]:
print(accuracy_score(y_test, y_pred))

0.9125


#### Classification Report

In [16]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.91      0.94        58
           1       0.80      0.91      0.85        22

    accuracy                           0.91        80
   macro avg       0.88      0.91      0.89        80
weighted avg       0.92      0.91      0.91        80



In [ ]:
# from six import StringIO
# from IPython.display import Image
# from sklearn.tree import export_graphviz
# import pydotplus
# dot_data = StringIO()
# export_graphviz(model,out_file=dot_data,
#                filled=True, rounded=True,
#                special_characters=True)
# graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
# Image(graph.create_png())

#### Model Training using criteria entropy

In [17]:
from sklearn.tree import DecisionTreeClassifier
model1 = DecisionTreeClassifier(criterion='entropy')
model1.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

#### Testing the model

In [18]:
y_pred1 = model1.predict(X_test)

#### Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred1)
print(cm)

[[53  5]
 [ 1 21]]


#### Accuracy Score

In [20]:
print(accuracy_score(y_test, y_pred1))

0.925


#### Classification Report

In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.91      0.94        58
           1       0.80      0.91      0.85        22

    accuracy                           0.91        80
   macro avg       0.88      0.91      0.89        80
weighted avg       0.92      0.91      0.91        80

